query AllEvents {
  allEvents(applicationId:"appId") {
    items {
      id
      timestamp
      dateCreated
      keys {
        key
        value
      }
    }
  }
}

query EventGroupByKeys {
  eventGroupByKeys(
    applicationId:"appId"
    window:DAY
    timestamp:99997200
    grouping:"eventType|campaignId|ipAddress"
    keys: [
      { key:"eventType", value:"click"},
      { key:"campaignId", value:"someValue"},
      { key:"ipaddress", value:"2.3.4.5"}
    ]
  ) {
    hash
    applicationId
    count
    window
    grouping
    nestedGroupings
  }
}

query CountEventsByGroup {
  countEventsByGroup(
    applicationId:"appId"
    window:DAY
    startTimestamp:99997200
    endTimestamp:100051200
    grouping:"eventType|campaignId|ipAddress"
    nestedGrouping: "eventType|campaignId"
  ) {
    aggregateCount
    recordCount
  }
}

query EventGroups {
  eventGroups(
    applicationId:"app2"
    window:HOUR
    startTimestamp:99997200
    endTimestamp:100051200
  ) {
    totalCount
    items {
      hash
      count
      events(limit: 2, skip: 1) {
        rawTimestamp
        timestamp
        ipAddress
      }
    }
  }
}

mutation LogEvent {
  logEvent(
    applicationId: "app2"
    newEvent: {
      keys: [
        { key: "eventType", value: "click" },
        { key: "ipAddress", value: "1.2.3.4" },
        { key: "userAgent", value: "Some Very Long User Agent" },
        { key: "campaignId", value: "someOtherValue" }
      ],
      timestamp: 100000000
    }) {
    success
    insertedId
  }
}

query AllConfigs {
  allConfigs {
    items {
      applicationId
      groups
      windows
    }
  }
}

query ConfigById {
  configByApplicationId(applicationId:"appId") {
    applicationId
    windows
    groups
  }
}

mutation CreateConfig {
  createConfig(newConfig: {
    applicationId: "appId"
    windows: [DAY, HOUR]
    groups:[
      "eventType",
    	"eventType|campaignId",
    ]
  }) {
    applicationId
  }
}

mutation UpdateConfig {
  updateConfig(
    applicationId: "appId",
    updateConfig: {
      windows: [HOUR, ALL_TIME]
      groups: [
        "eventType",
    	  "eventType|campaignId",
      ]
  }) {
    applicationId
    windows
    groups
  }
}

mutation RemoveConfig {
  deleteConfig(applicationId: "appId") {
    success
  }
}

