query AllEvents {
  allEvents(applicationId:"appId") {
    items {
      id
      timestamp
      dateCreated
      keys {
        key
        value
      }
    }
  }
}

query EventGroupByKeys {
  eventGroupByKeys(
    applicationId:"appId"
    window:DAY
    timestamp:99964800
    group:"eventType|campaignId"
    keys: [
      { key:"eventType", value:"click"},
      { key:"campaignId", value:"someValue"},
    ]
  ) {
    hash
    applicationId
  }
}

mutation LogEvent {
  logEvent(
    applicationId: "app2"
    newEvent: {
      keys: [
        { key: "eventType", value: "click" },
        { key: "ipAddress", value: "3.2.3.4" },
        { key: "userAgent", value: "Some Very Long User Agent" },
        { key: "campaignId", value: "someOtherValue" }
      ],
      timestamp: 100000000
    }) {
    id
    timestamp
  }
}

query AllConfigs {
  allConfigs {
    items {
      applicationId
      groups
      windows
    }
  }
}

query ConfigById {
  configByApplicationId(applicationId:"appId") {
    applicationId
    windows
    groups
  }
}

mutation CreateConfig {
  createConfig(newConfig: {
    applicationId: "app2"
    windows: [DAY, HOUR]
    groups:[
      "eventType",
    	"eventType|campaignId",
    ]
  }) {
    applicationId
  }
}

mutation UpdateConfig {
  updateConfig(
    applicationId: "app2",
    updateConfig: {
      windows: [HOUR, ALL_TIME]
      groups: [
        "eventType",
    	  "eventType|campaignId",
      ]
  }) {
    applicationId
    windows
    groups
  }
}

mutation RemoveConfig {
  deleteConfig(applicationId: "appId") {
    success
  }
}

